'use strict';

registerVocabularyPack('CH', {
    'app.login_title':'登录 AI Civilization', 'app.register_title':'注册 AI Civilization',
    'common.none':'无', 'common.open':'已发现', 'common.clear':'清除', 'common.close':'关闭',
    'common.waiting':'等待中', 'common.overall':'总计', 'common.type':'类型', 'common.count':'数量',
    'common.health':'生命', 'common.you':'你',
    'hud.food_storage':'粮食储备', 'hud.gold_storage':'国库', 'hud.end_turn':'结束回合',
    'hud.turn_seconds':'{action}（{seconds}秒）', 'hud.options':'选项', 'hud.log_out':'退出登录',
    'hud.logging_out':'正在退出...', 'hud.respawn':'重新出生', 'hud.back_to_game':'返回游戏',
    'hud.respawn_prompt':'点击小地图选择重新出生点', 'hud.respawning':'文明正在重新出生...',
    'menu.action_options':'行动：', 'menu.technology':'科技', 'menu.politics':'政治', 'menu.finance':'财政',
    'menu.trade':'贸易', 'menu.ai_console':'AI 控制台', 'menu.ai_console_status':'模型决策与已执行命令',
    'menu.costs':'费用', 'menu.turn_costs':'回合费用', 'menu.civilizations':'文明', 'menu.civs':'文明',
    'command.goto':'前往', 'command.fortificate':'驻防', 'command.fortification':'建造堡垒',
    'command.road':'道路', 'command.road_to':'铺路至', 'command.pasture':'牧场', 'command.farm':'农场',
    'command.plantation':'种植园', 'command.camp':'营地', 'command.fishing_boats':'渔船',
    'command.network':'渔网', 'command.quarry':'采石场', 'command.winery':'酿酒厂',
    'command.cottage':'村舍', 'command.workshop':'工坊', 'command.mine':'矿山',
    'command.disband':'解散', 'command.wait':'等待', 'command.irrigate':'灌溉',
    'command.chop_forest':'砍伐森林', 'command.build_city':'建立城市', 'command.explore':'探索',
    'command.patrol':'巡逻', 'command.automate':'自动行动', 'command.optimize_food':'优先粮食',
    'command.optimize_production':'优先生产', 'command.optimize_gold':'优先金币',
    'command.optimize_balanced':'均衡分配', 'command.clear_backlog':'清空队列',
    'command.select_all':'全部选择', 'command.select_all_title':'选择此地块上的所有军事单位',
    'production.none_selected':'未选择生产', 'production.backlog':'队列：', 'production.backlog_empty':'队列：空',
    'production.blocked_money':'生产受阻：国库为负', 'production.turns':'{count} 回合',
    'production.status':'{name}（{turns} 回合）',
    'production.paused_status':'{name}（暂停：产=0）',
    'production.city_economy':' 人口:{population} 粮:{food} 产:{production} 金:{money} 消耗:{consumption} 增长:{growth}',
    'production.focus':' 重点：{focus}', 'production.current_suffix':'（当前）',
    'production.option':'{name}（{cost}）{attack}/{defense}/{speed} | 消耗 F:{food} G:{gold}',
    'unit.settlers':'定居者', 'unit.worker':'工人', 'unit.explorer':'探索者', 'unit.warrior':'勇士',
    'unit.slinger':'投石兵', 'unit.archer':'弓箭手', 'unit.spearman':'长矛兵', 'unit.horseman':'骑手',
    'unit.chariot':'战车', 'unit.elephant':'战象', 'unit.catapult':'投石车', 'unit.trebuchet':'重力抛石机',
    'unit.galley':'桨帆船', 'unit.galleon':'大帆船', 'unit.workboat':'工作船', 'unit.frigate':'护卫舰',
    'unit.knight':'骑士', 'unit.pikeman':'长枪兵', 'unit.longbow':'长弓兵', 'unit.fencer':'剑客',
    'unit.swordsman':'剑士', 'unit.trireme':'三列桨战船', 'unit.city':'城市',
    'unit.destroyed_city':'被摧毁的城市', 'unit.generic':'单位', 'unit.city_badge':'城市',
    'unit.units_count':'单位（{count}）', 'unit.units_at':'位于 {i}, {j} 的单位',
    'unit.features':'{attack}/{defense}/{speed}', 'unit.selected_military':'已选军事单位：{count}',
    'unit.id':'单位 ID：{id}', 'unit.pending':'等待中',
    'terrain.water':'水域', 'terrain.sand':'沙地', 'terrain.grass':'草原', 'terrain.snow':'雪地',
    'terrain.hills':'丘陵', 'terrain.mountains':'山脉', 'terrain.forest':'森林',
    'terrain.grasswater':'有水草原', 'terrain.unknown':'未知',
    'tile.defence':'防御', 'tile.base':'基础', 'tile.resource':'资源', 'tile.current':'当前',
    'tile.suggested':'建议', 'tile.after':'建成后', 'tile.income':'粮食 {food} / 生产 {production} / 金币 {gold}',
    'cost.unit_upkeep':'单位维护', 'cost.city_balances':'城市每回合收支',
    'cost.city':'城市', 'cost.population':'人口', 'cost.producing':'生产',
    'cost.balance_food_production_gold':'收支 粮/产/金', 'cost.no_cities':'没有城市',
    'cost.improvement_upkeep':'改良设施维护',
    'cost.each_food_gold':'每个 粮/金', 'cost.total_food_gold':'总计 粮/金',
    'cost.each_food_production_gold':'每个 粮/产/金', 'cost.total_food_production_gold':'总计 粮/产/金',
    'cost.no_units':'没有单位',
    'civilization.coat_title':'{name} 的纹章', 'civilization.own_suffix':'（{you}）',
    'civilization.units_cities':'单位：{units} | 城市：{cities}',
    'civilization.food_gold':'粮食：{food} | 金币：{gold}',
    'civilization.results':'击杀：{killed} | 占领：{occupied} | 摧毁：{destroyed}',
    'civilization.relation_to_you':'与你的关系：{relation}',
    'relation.friend':'友好', 'relation.enemy':'敌对', 'relation.neutral':'中立', 'relation.self':'本国',
    'technology.science_rate':'科研：{rate}%', 'technology.research_unavailable':'无法研究',
    'technology.status':'科技：{name} {progress}/{cost}', 'technology.all_discovered':'所有科技均已发现',
    'technology.Mining':'采矿', 'technology.Pottery':'制陶', 'technology.Animal Husbandry':'畜牧',
    'technology.Sailing':'航海', 'technology.Masonry':'砖石建筑', 'technology.Bronze Working':'青铜加工',
    'technology.Irrigation':'灌溉', 'technology.Writing':'文字', 'technology.Archery':'箭术',
    'technology.Wheel':'车轮', 'technology.Astronomy':'天文学', 'technology.Currency':'货币',
    'technology.Horseback Riding':'骑术', 'technology.Iron Working':'铁器加工',
    'technology.Shipbuilding':'造船', 'technology.Mathematics':'数学', 'technology.Navigation':'导航',
    'technology.Construction':'建筑', 'technology.Engineering':'工程学',
    'resource.bananas':'香蕉', 'resource.cattle':'牛', 'resource.copper':'铜', 'resource.crabs':'螃蟹',
    'resource.deer':'鹿', 'resource.fish':'鱼', 'resource.rice':'稻米', 'resource.sheep':'绵羊',
    'resource.stone':'石料', 'resource.wheat':'小麦', 'resource.amber':'琥珀', 'resource.citrus':'柑橘',
    'resource.cotton':'棉花', 'resource.dyes':'染料', 'resource.diamonds':'钻石', 'resource.furs':'毛皮',
    'resource.gypsum':'石膏', 'resource.honey':'蜂蜜', 'resource.incense':'熏香', 'resource.ivory':'象牙',
    'resource.marble':'大理石', 'resource.olives':'橄榄', 'resource.pearls':'珍珠', 'resource.salt':'盐',
    'resource.silk':'丝绸', 'resource.silver':'白银', 'resource.spices':'香料', 'resource.sugar':'糖',
    'resource.tea':'茶', 'resource.turtles':'海龟', 'resource.whales':'鲸', 'resource.wine':'葡萄酒',
    'resource.horses':'马', 'resource.iron':'铁', 'resource.gold':'黄金', 'resource.gems':'宝石',
    'turn.end_ai_user':'结束 AI 玩家 {id} 的回合', 'turn.end_user':'结束玩家 {id} 的回合',
    'auth.login_or_email':'用户名或电子邮件', 'auth.login':'登录', 'auth.email_optional':'电子邮件（可选）',
    'auth.password':'密码', 'auth.remember_me':'记住我', 'auth.register':'注册',
    'auth.register_heading':'注册玩家', 'auth.register_new':'注册新玩家', 'auth.return_login':'返回登录',
    'auth.login_failed':'登录失败。', 'auth.registration_failed':'注册失败。',
    'auth.cookie_rejected':'浏览器拒绝了游戏会话 Cookie。请允许此网站使用 Cookie。',
    'auth.session_expired':'登录会话已过期，请重新登录。', 'auth.invalid_session':'登录会话无效，请重新登录。',
    'auth.authentication_required':'请登录后继续。', 'auth.account_unavailable':'此账号当前不可用。',
    'message.disband_pending':'单位 #{id} 将在回合结束时解散。',
    'message.unit_destroyed_funds':'单位“{name}”因资金不足而被解散。',
    'message.worker_command_unavailable':'工人 #{id} 无法在此地块执行“{command}”。',
    'message.preparing_ai':'正在准备 AI 玩家 {id}...', 'message.ai_not_ready':'AI 玩家 {id} 尚未准备好'
});
