'use strict';

var _game_vocabulary_packs = typeof _game_vocabulary_packs === 'undefined' ? {} : _game_vocabulary_packs;
_game_vocabulary_packs.EN = {
        'app.name': 'AI Civilization',
        'app.login_title': 'AI Civilization Login',
        'app.register_title': 'Register AI Civilization Player',

        'common.none': 'None',
        'common.open': 'Open',
        'common.clear': 'Clear',
        'common.close': 'Close',
        'common.waiting': 'Waiting',
        'common.overall': 'Overall',
        'common.type': 'Type',
        'common.count': 'Count',
        'common.health': 'Health',
        'common.you': 'you',

        'hud.food_storage': 'Food storage',
        'hud.gold_storage': 'Gold storage',
        'hud.end_turn': 'End Turn',
        'hud.turn_seconds': '{action} ({seconds}s)',
        'hud.options': 'Options',
        'hud.log_out': 'Log out',
        'hud.logging_out': 'Logging Out...',
        'hud.respawn': 'Respawn',
        'hud.back_to_game': 'Back to game',
        'hud.respawn_prompt': 'Click on minimap to select respawn point',
        'hud.respawning': 'Respawning civilization...',

        'menu.action_options': 'Action options:',
        'menu.technology': 'Technology',
        'menu.politics': 'Politics',
        'menu.finance': 'Finance',
        'menu.trade': 'Trade',
        'menu.ai_console': 'AI Console',
        'menu.ai_console_status': 'Model decisions and applied orders',
        'menu.costs': 'Costs',
        'menu.turn_costs': 'Turn costs',
        'menu.civilizations': 'Civilizations',
        'menu.civs': 'Civs',

        'command.goto': 'Goto',
        'command.fortificate': 'Fortificate',
        'command.fortification': 'Fortification',
        'command.road': 'Road',
        'command.road_to': 'Road-to',
        'command.pasture': 'Pasture',
        'command.farm': 'Farm',
        'command.plantation': 'Plantation',
        'command.camp': 'Camp',
        'command.fishing_boats': 'Fishing Boats',
        'command.network': 'Nets',
        'command.quarry': 'Quarry',
        'command.winery': 'Winery',
        'command.cottage': 'Cottage',
        'command.workshop': 'Workshop',
        'command.mine': 'Mine',
        'command.disband': 'Disband',
        'command.wait': 'Wait',
        'command.irrigate': 'Irrigate',
        'command.chop_forest': 'Chop forest',
        'command.build_city': 'Build City',
        'command.explore': 'Explore',
        'command.patrol': 'Patrol',
        'command.automate': 'Automate',
        'command.optimize_food': 'Optimize for food',
        'command.optimize_production': 'Optimize for production',
        'command.optimize_gold': 'Optimize for gold',
        'command.optimize_balanced': 'Optimize for all',
        'command.clear_backlog': 'Clear backlog',
        'command.select_all': 'Select all',
        'command.select_all_title': 'Select all military units on this Tile',

        'command_key.goto': 'G',
        'command_key.fortificate': 'F',
        'command_key.fortification': 'F',
        'command_key.road': 'R',
        'command_key.road_to': 'J',
        'command_key.pasture': 'P',
        'command_key.farm': 'Y',
        'command_key.plantation': 'N',
        'command_key.camp': 'K',
        'command_key.fishing_boats': 'O',
        'command_key.network': 'N',
        'command_key.quarry': 'Q',
        'command_key.winery': 'V',
        'command_key.cottage': 'T',
        'command_key.workshop': 'S',
        'command_key.mine': 'M',
        'command_key.disband': 'D',
        'command_key.wait': 'W',
        'command_key.irrigate': 'I',
        'command_key.chop_forest': 'C',
        'command_key.build_city': 'B',
        'command_key.explore': 'E',
        'command_key.patrol': 'L',
        'command_key.automate': 'A',

        'production.none_selected': 'None selected',
        'production.backlog': 'Backlog:',
        'production.backlog_empty': 'Backlog: empty',
        'production.blocked_money': 'Production blocked: negative money account',
        'production.turns': '{count} turns',
        'production.status': '{name} ({turns} turns)',
        'production.paused_status': '{name} (paused: P=0)',
        'production.city_economy': ' Pop:{population} F:{food} P:{production} M:{money} Eat:{consumption} Growth:{growth}',
        'production.focus': ' Focus: {focus}',
        'production.current_suffix': ' (current)',
        'production.option': '{name} ({cost}) {attack}/{defense}/{speed} | Costs F:{food} G:{gold}',
        'production.building_option': '{name} ({cost})',
        'production.built_buildings': 'Built buildings:',

        'unit.settlers': 'Settlers',
        'unit.worker': 'Worker',
        'unit.explorer': 'Explorer',
        'unit.warrior': 'Warrior',
        'unit.slinger': 'Slinger',
        'unit.archer': 'Archer',
        'unit.spearman': 'Spearman',
        'unit.horseman': 'Horseman',
        'unit.chariot': 'Chariot',
        'unit.elephant': 'Elephant',
        'unit.catapult': 'Catapult',
        'unit.trebuchet': 'Trebuchet',
        'unit.galley': 'Galley',
        'unit.galleon': 'Galleon',
        'unit.workboat': 'WorkBoat',
        'unit.frigate': 'Frigate',
        'unit.knight': 'Knight',
        'unit.pikeman': 'Pikeman',
        'unit.longbow': 'Longbow',
        'unit.fencer': 'Fencer',
        'unit.swordsman': 'Swordsman',
        'unit.trireme': 'Trireme',
        'unit.city': 'City',
        'unit.destroyed_city': 'Destroyed City',
        'unit.lazaret': 'Lazaret',
        'unit.stable': 'Stable',
        'unit.shooting_range': 'Shooting-range',
        'unit.barracks': 'Barracks',
        'unit.port': 'Port',
        'unit.market': 'Market',
        'unit.generic': 'Unit',
        'unit.city_badge': 'CITY',
        'unit.units_count': 'Units ({count})',
        'unit.units_at': 'Units at {i}, {j}',
        'unit.features': '{attack}/{defense}/{speed}',
        'unit.selected_military': 'Selected military units: {count}',
        'unit.id': 'Unit ID: {id}',
        'unit.pending': 'pending',
        'unit.health_experience': '{features} HP:{health}/{maxHealth} XP:{experience}',

        'terrain.water': 'Water',
        'terrain.sand': 'Sand',
        'terrain.grass': 'Grass',
        'terrain.snow': 'Snow',
        'terrain.hills': 'Hills',
        'terrain.mountains': 'Mountains',
        'terrain.forest': 'Forest',
        'terrain.grasswater': 'Grass with water',
        'terrain.unknown': 'Unknown',

        'tile.defence': 'Defence',
        'tile.base': 'Base',
        'tile.resource': 'Resource',
        'tile.current': 'Current',
        'tile.suggested': 'Suggested',
        'tile.after': 'After',
        'tile.income': 'Food {food} / Shields {production} / Gold {gold}',

        'cost.unit_upkeep': 'Unit upkeep',
        'cost.city_balances': 'City balances per turn',
        'cost.city': 'City',
        'cost.population': 'Pop.',
        'cost.producing': 'Producing',
        'cost.balance_food_production_gold': 'Balance F/P/G',
        'cost.no_cities': 'No cities',
        'cost.improvement_upkeep': 'Improvement upkeep',
        'cost.each_food_gold': 'Each F/G',
        'cost.total_food_gold': 'Total F/G',
        'cost.each_food_production_gold': 'Each F/P/G',
        'cost.total_food_production_gold': 'Total F/P/G',
        'cost.no_units': 'No units',

        'civilization.coat_title': '{name} coat of arms',
        'civilization.own_suffix': ' ({you})',
        'civilization.units_cities': 'Units: {units} | Cities: {cities}',
        'civilization.food_gold': 'Food: {food} | Gold: {gold}',
        'civilization.results': 'Killed: {killed} | Occupied: {occupied} | Destroyed: {destroyed}',
        'civilization.relation_to_you': 'Relation to you: {relation}',
        'relation.friend': 'Friend',
        'relation.enemy': 'Enemy',
        'relation.neutral': 'Neutral',
        'relation.self': 'Self',

        'technology.science_rate': 'Science: {rate}%',
        'technology.research_unavailable': 'Research: unavailable',
        'technology.status': 'Technology: {name} {progress}/{cost}',
        'technology.all_discovered': 'Technology: all discovered',

        'technology.Mining': 'Mining',
        'technology.Pottery': 'Pottery',
        'technology.Animal Husbandry': 'Animal Husbandry',
        'technology.Sailing': 'Sailing',
        'technology.Masonry': 'Masonry',
        'technology.Bronze Working': 'Bronze Working',
        'technology.Irrigation': 'Irrigation',
        'technology.Writing': 'Writing',
        'technology.Archery': 'Archery',
        'technology.Wheel': 'Wheel',
        'technology.Astronomy': 'Astronomy',
        'technology.Currency': 'Currency',
        'technology.Horseback Riding': 'Horseback Riding',
        'technology.Iron Working': 'Iron Working',
        'technology.Shipbuilding': 'Shipbuilding',
        'technology.Mathematics': 'Mathematics',
        'technology.Navigation': 'Navigation',
        'technology.Construction': 'Construction',
        'technology.Engineering': 'Engineering',

        'resource.bananas': 'Bananas',
        'resource.cattle': 'Cattle',
        'resource.copper': 'Copper',
        'resource.crabs': 'Crabs',
        'resource.deer': 'Deer',
        'resource.fish': 'Fish',
        'resource.rice': 'Rice',
        'resource.sheep': 'Sheep',
        'resource.stone': 'Stone',
        'resource.wheat': 'Wheat',
        'resource.amber': 'Amber',
        'resource.citrus': 'Citrus',
        'resource.cotton': 'Cotton',
        'resource.dyes': 'Dyes',
        'resource.diamonds': 'Diamonds',
        'resource.furs': 'Furs',
        'resource.gypsum': 'Gypsum',
        'resource.honey': 'Honey',
        'resource.incense': 'Incense',
        'resource.ivory': 'Ivory',
        'resource.marble': 'Marble',
        'resource.olives': 'Olives',
        'resource.pearls': 'Pearls',
        'resource.salt': 'Salt',
        'resource.silk': 'Silk',
        'resource.silver': 'Silver',
        'resource.spices': 'Spices',
        'resource.sugar': 'Sugar',
        'resource.tea': 'Tea',
        'resource.turtles': 'Turtles',
        'resource.whales': 'Whales',
        'resource.wine': 'Wine',
        'resource.horses': 'Horses',
        'resource.iron': 'Iron',
        'resource.gold': 'Gold',
        'resource.gems': 'Gems',

        'resource_description.bananas': 'food from tropical forest and grass tiles',
        'resource_description.cattle': 'food and production from grassland herds',
        'resource_description.copper': 'early metal production and trade value',
        'resource_description.crabs': 'food from coastal water and river grass',
        'resource_description.deer': 'food and hides from forest or snow edge tiles',
        'resource_description.fish': 'food from water tiles',
        'resource_description.rice': 'food from wet grass and river grass',
        'resource_description.sheep': 'food and wool from grass or hills',
        'resource_description.stone': 'production support for early buildings and construction',
        'resource_description.wheat': 'food support for city growth',
        'resource_description.amber': 'luxury and trade value from forested lands',
        'resource_description.citrus': 'food and luxury from warm grass or forest',
        'resource_description.cotton': 'luxury and textile value from open land',
        'resource_description.dyes': 'luxury and trade colorants from forests or grass',
        'resource_description.diamonds': 'high-value luxury from hills and rocks',
        'resource_description.furs': 'luxury from cold terrain and forests',
        'resource_description.gypsum': 'construction material from desert, hills, and rocks',
        'resource_description.honey': 'food and luxury from forest and grass',
        'resource_description.incense': 'luxury and ceremonial trade value',
        'resource_description.ivory': 'luxury and strategic animal material',
        'resource_description.marble': 'luxury stone and building production value',
        'resource_description.olives': 'food and luxury from grass or hills',
        'resource_description.pearls': 'luxury from water tiles',
        'resource_description.salt': 'food preservation and trade value',
        'resource_description.silk': 'luxury textile value from forest regions',
        'resource_description.silver': 'precious metal commerce and trade value',
        'resource_description.spices': 'luxury and food trade value',
        'resource_description.sugar': 'food and luxury from wet grass or river grass',
        'resource_description.tea': 'luxury from hills or forest',
        'resource_description.turtles': 'food and luxury from water tiles',
        'resource_description.whales': 'food, production, and luxury from water tiles',
        'resource_description.wine': 'luxury and culture value from grass or hills',
        'resource_description.horses': 'strategic animal resource for horse units',
        'resource_description.iron': 'strategic metal for iron weapons and units',
        'resource_description.gold': 'commerce and trade value',
        'resource_description.gems': 'valuable minerals for luxury and trade',

        'turn.end_ai_user': 'End AI User {id} Turn',
        'turn.end_user': 'End User {id} Turn',

        'auth.login_heading': 'AI Civilization',
        'auth.login_or_email': 'Login or email',
        'auth.login': 'Login',
        'auth.email_optional': 'Email (optional)',
        'auth.password': 'Password',
        'auth.remember_me': 'Remember me',
        'auth.register': 'Register',
        'auth.register_heading': 'Register Player',
        'auth.register_new': 'Register a new player',
        'auth.return_login': 'Return to login',
        'auth.login_failed': 'Login failed.',
        'auth.registration_failed': 'Registration failed.',
        'auth.cookie_rejected': 'The browser rejected the game session cookie. Enable cookies for this site.',
        'auth.session_replaced': 'This account was signed in on another device. Please log in again here to continue.',
        'auth.session_expired': 'Your login session expired. Please log in again.',
        'auth.invalid_session': 'Your login session is invalid. Please log in again.',
        'auth.authentication_required': 'Please log in to continue.',
        'auth.account_unavailable': 'This account is not currently available.',

        'message.disband_pending': 'Unit #{id} will be disbanded at End Turn.',
        'message.unit_destroyed_funds': 'Unit "{name}" is destroyed due to lack of funds.',
        'message.worker_command_unavailable': '{command} is not available for Worker #{id} on this Tile.',
        'message.preparing_ai': 'Preparing AI User {id}...',
        'message.ai_not_ready': 'AI User {id} not ready'
};

function registerVocabularyPack(language, words)
{
    _game_vocabulary_packs[language] = Object.assign({}, _game_vocabulary_packs.EN, words || {});
}
