'use strict';

registerVocabularyPack('DE', {
    'app.login_title':'AI Civilization Anmeldung', 'app.register_title':'AI Civilization Registrierung',
    'common.none':'Keine', 'common.open':'Erforscht', 'common.clear':'Leeren', 'common.close':'Schließen',
    'common.waiting':'Warten', 'common.overall':'Gesamt', 'common.type':'Typ', 'common.count':'Anzahl',
    'common.health':'Gesundheit', 'common.you':'Sie',
    'hud.food_storage':'Nahrungsvorrat', 'hud.gold_storage':'Goldschatz', 'hud.end_turn':'Runde beenden',
    'hud.turn_seconds':'{action} ({seconds}s)', 'hud.options':'Optionen', 'hud.log_out':'Abmelden',
    'hud.logging_out':'Abmeldung...', 'hud.respawn':'Neu starten', 'hud.back_to_game':'Zurück zum Spiel',
    'hud.respawn_prompt':'Klicken Sie auf die Minikarte, um einen Startpunkt zu wählen',
    'hud.respawning':'Zivilisation wird neu gestartet...',
    'menu.action_options':'Aktionen:', 'menu.technology':'Technologie', 'menu.politics':'Politik',
    'menu.finance':'Finanzen', 'menu.trade':'Handel', 'menu.ai_console':'KI-Konsole',
    'menu.ai_console_status':'Modellentscheidungen und ausgeführte Befehle', 'menu.costs':'Kosten',
    'menu.turn_costs':'Rundenkosten', 'menu.civilizations':'Zivilisationen', 'menu.civs':'Zivs',
    'command.goto':'Gehe zu', 'command.fortificate':'Verschanzen', 'command.fortification':'Befestigung',
    'command.road':'Straße', 'command.road_to':'Straße nach', 'command.pasture':'Weide', 'command.farm':'Bauernhof',
    'command.plantation':'Plantage', 'command.camp':'Lager', 'command.fishing_boats':'Fischerboote',
    'command.network':'Netze', 'command.quarry':'Steinbruch', 'command.winery':'Weingut',
    'command.cottage':'Hütte', 'command.workshop':'Werkstatt', 'command.mine':'Mine',
    'command.disband':'Auflösen', 'command.wait':'Warten', 'command.irrigate':'Bewässern',
    'command.chop_forest':'Wald roden', 'command.build_city':'Stadt gründen', 'command.explore':'Erkunden',
    'command.patrol':'Patrouillieren', 'command.automate':'Automatisieren',
    'command.optimize_food':'Auf Nahrung optimieren', 'command.optimize_production':'Auf Produktion optimieren',
    'command.optimize_gold':'Auf Gold optimieren', 'command.optimize_balanced':'Ausgleichen',
    'command.clear_backlog':'Warteschlange leeren', 'command.select_all':'Alle auswählen',
    'command.select_all_title':'Alle Militäreinheiten auf diesem Feld auswählen',
    'production.none_selected':'Keine Produktion', 'production.backlog':'Warteschlange:',
    'production.backlog_empty':'Warteschlange: leer', 'production.blocked_money':'Produktion blockiert: negatives Konto',
    'production.turns':'{count} Runden', 'production.status':'{name} ({turns} Runden)',
    'production.paused_status':'{name} (pausiert: P=0)',
    'production.city_economy':' Bev:{population} N:{food} P:{production} G:{money} Verbr:{consumption} Wachs:{growth}',
    'production.focus':' Schwerpunkt: {focus}', 'production.current_suffix':' (aktuell)',
    'production.option':'{name} ({cost}) {attack}/{defense}/{speed} | Kosten F:{food} G:{gold}',
    'unit.settlers':'Siedler', 'unit.worker':'Arbeiter', 'unit.explorer':'Entdecker', 'unit.warrior':'Krieger',
    'unit.slinger':'Schleuderer', 'unit.archer':'Bogenschütze', 'unit.spearman':'Speerkämpfer',
    'unit.horseman':'Reiter', 'unit.chariot':'Streitwagen', 'unit.elephant':'Elefant',
    'unit.catapult':'Katapult', 'unit.trebuchet':'Tribok', 'unit.galley':'Galeere', 'unit.galleon':'Galeone',
    'unit.workboat':'Arbeitsboot', 'unit.frigate':'Fregatte', 'unit.knight':'Ritter', 'unit.pikeman':'Pikenier',
    'unit.longbow':'Langbogenschütze', 'unit.fencer':'Fechter', 'unit.swordsman':'Schwertkämpfer',
    'unit.trireme':'Triere', 'unit.city':'Stadt', 'unit.destroyed_city':'Zerstörte Stadt',
    'unit.generic':'Einheit', 'unit.city_badge':'STADT', 'unit.units_count':'Einheiten ({count})',
    'unit.units_at':'Einheiten bei {i}, {j}', 'unit.features':'{attack}/{defense}/{speed}',
    'unit.selected_military':'Ausgewählte Militäreinheiten: {count}', 'unit.id':'Einheiten-ID: {id}',
    'unit.pending':'ausstehend',
    'terrain.water':'Wasser', 'terrain.sand':'Sand', 'terrain.grass':'Grasland', 'terrain.snow':'Schnee',
    'terrain.hills':'Hügel', 'terrain.mountains':'Gebirge', 'terrain.forest':'Wald',
    'terrain.grasswater':'Feuchtes Grasland', 'terrain.unknown':'Unbekannt',
    'tile.defence':'Verteidigung', 'tile.base':'Basis', 'tile.resource':'Ressource', 'tile.current':'Aktuell',
    'tile.suggested':'Empfohlen', 'tile.after':'Danach',
    'tile.income':'Nahrung {food} / Schilde {production} / Gold {gold}',
    'cost.unit_upkeep':'Einheitenunterhalt', 'cost.city_balances':'Stadtbilanzen pro Runde',
    'cost.city':'Stadt', 'cost.population':'Bev.', 'cost.producing':'Produktion',
    'cost.balance_food_production_gold':'Bilanz N/P/G', 'cost.no_cities':'Keine Städte',
    'cost.improvement_upkeep':'Ausbauunterhalt',
    'cost.each_food_gold':'Je N/G', 'cost.total_food_gold':'Gesamt N/G',
    'cost.each_food_production_gold':'Je N/P/G', 'cost.total_food_production_gold':'Gesamt N/P/G',
    'cost.no_units':'Keine Einheiten',
    'civilization.coat_title':'Wappen von {name}', 'civilization.own_suffix':' ({you})',
    'civilization.units_cities':'Einheiten: {units} | Städte: {cities}',
    'civilization.food_gold':'Nahrung: {food} | Gold: {gold}',
    'civilization.results':'Getötet: {killed} | Besetzt: {occupied} | Zerstört: {destroyed}',
    'civilization.relation_to_you':'Beziehung zu Ihnen: {relation}',
    'relation.friend':'Freund', 'relation.enemy':'Feind', 'relation.neutral':'Neutral', 'relation.self':'Eigen',
    'technology.science_rate':'Forschung: {rate}%', 'technology.research_unavailable':'Forschung nicht verfügbar',
    'technology.status':'Technologie: {name} {progress}/{cost}',
    'technology.all_discovered':'Alle Technologien erforscht',
    'technology.Mining':'Bergbau', 'technology.Pottery':'Töpferei', 'technology.Animal Husbandry':'Tierzucht',
    'technology.Sailing':'Segeln', 'technology.Masonry':'Maurerhandwerk',
    'technology.Bronze Working':'Bronzeverarbeitung', 'technology.Irrigation':'Bewässerung',
    'technology.Writing':'Schrift', 'technology.Archery':'Bogenschießen', 'technology.Wheel':'Rad',
    'technology.Astronomy':'Astronomie', 'technology.Currency':'Währung', 'technology.Horseback Riding':'Reitkunst',
    'technology.Iron Working':'Eisenverarbeitung', 'technology.Shipbuilding':'Schiffbau',
    'technology.Mathematics':'Mathematik', 'technology.Navigation':'Navigation',
    'technology.Construction':'Bauwesen', 'technology.Engineering':'Ingenieurwesen',
    'resource.bananas':'Bananen', 'resource.cattle':'Rinder', 'resource.copper':'Kupfer', 'resource.crabs':'Krabben',
    'resource.deer':'Hirsche', 'resource.fish':'Fisch', 'resource.rice':'Reis', 'resource.sheep':'Schafe',
    'resource.stone':'Stein', 'resource.wheat':'Weizen', 'resource.amber':'Bernstein', 'resource.citrus':'Zitrusfrüchte',
    'resource.cotton':'Baumwolle', 'resource.dyes':'Farbstoffe', 'resource.diamonds':'Diamanten',
    'resource.furs':'Pelze', 'resource.gypsum':'Gips', 'resource.honey':'Honig', 'resource.incense':'Weihrauch',
    'resource.ivory':'Elfenbein', 'resource.marble':'Marmor', 'resource.olives':'Oliven', 'resource.pearls':'Perlen',
    'resource.salt':'Salz', 'resource.silk':'Seide', 'resource.silver':'Silber', 'resource.spices':'Gewürze',
    'resource.sugar':'Zucker', 'resource.tea':'Tee', 'resource.turtles':'Schildkröten', 'resource.whales':'Wale',
    'resource.wine':'Wein', 'resource.horses':'Pferde', 'resource.iron':'Eisen', 'resource.gold':'Gold',
    'resource.gems':'Edelsteine',
    'turn.end_ai_user':'KI-Spieler {id} beenden', 'turn.end_user':'Runde von Spieler {id} beenden',
    'auth.login_or_email':'Anmeldename oder E-Mail', 'auth.login':'Anmelden',
    'auth.email_optional':'E-Mail (optional)', 'auth.password':'Passwort', 'auth.remember_me':'Angemeldet bleiben',
    'auth.register':'Registrieren', 'auth.register_heading':'Spieler registrieren',
    'auth.register_new':'Neuen Spieler registrieren', 'auth.return_login':'Zurück zur Anmeldung',
    'auth.login_failed':'Anmeldung fehlgeschlagen.', 'auth.registration_failed':'Registrierung fehlgeschlagen.',
    'auth.cookie_rejected':'Der Browser hat das Sitzungscookie abgelehnt. Erlauben Sie Cookies für diese Website.',
    'auth.session_expired':'Ihre Sitzung ist abgelaufen. Bitte melden Sie sich erneut an.',
    'auth.invalid_session':'Ihre Sitzung ist ungültig. Bitte melden Sie sich erneut an.',
    'auth.authentication_required':'Bitte melden Sie sich an.', 'auth.account_unavailable':'Dieses Konto ist nicht verfügbar.',
    'message.disband_pending':'Einheit #{id} wird am Rundenende aufgelöst.',
    'message.unit_destroyed_funds':'Einheit „{name}“ wurde wegen Geldmangels zerstört.',
    'message.worker_command_unavailable':'{command} ist für Arbeiter #{id} auf diesem Feld nicht verfügbar.',
    'message.preparing_ai':'KI-Spieler {id} wird vorbereitet...', 'message.ai_not_ready':'KI-Spieler {id} ist nicht bereit'
});
