'use strict';

registerVocabularyPack('FR', {
    'app.login_title':'Connexion à AI Civilization', 'app.register_title':'Inscription à AI Civilization',
    'common.none':'Aucun', 'common.open':'Découvert', 'common.clear':'Effacer', 'common.close':'Fermer',
    'common.waiting':'En attente', 'common.overall':'Total', 'common.type':'Type', 'common.count':'Nombre',
    'common.health':'Santé', 'common.you':'vous',
    'hud.food_storage':'Réserve de nourriture', 'hud.gold_storage':'Trésor', 'hud.end_turn':'Fin du tour',
    'hud.turn_seconds':'{action} ({seconds}s)', 'hud.options':'Options', 'hud.log_out':'Déconnexion',
    'hud.logging_out':'Déconnexion...', 'hud.respawn':'Réapparaître', 'hud.back_to_game':'Retour au jeu',
    'hud.respawn_prompt':'Cliquez sur la mini-carte pour choisir le point de réapparition',
    'hud.respawning':'Réapparition de la civilisation...',
    'menu.action_options':'Actions :', 'menu.technology':'Technologie', 'menu.politics':'Politique',
    'menu.finance':'Finances', 'menu.trade':'Commerce', 'menu.ai_console':'Console IA',
    'menu.ai_console_status':'Décisions du modèle et ordres appliqués', 'menu.costs':'Coûts',
    'menu.turn_costs':'Coûts du tour', 'menu.civilizations':'Civilisations', 'menu.civs':'Civs',
    'command.goto':'Aller', 'command.fortificate':'Fortifier', 'command.fortification':'Fortification',
    'command.road':'Route', 'command.road_to':'Route vers', 'command.pasture':'Pâturage',
    'command.farm':'Ferme', 'command.plantation':'Plantation', 'command.camp':'Camp',
    'command.fishing_boats':'Bateaux de pêche', 'command.network':'Filets', 'command.quarry':'Carrière',
    'command.winery':'Domaine viticole', 'command.cottage':'Chaumière', 'command.workshop':'Atelier',
    'command.mine':'Mine', 'command.disband':'Dissoudre', 'command.wait':'Attendre',
    'command.irrigate':'Irriguer', 'command.chop_forest':'Défricher', 'command.build_city':'Fonder une ville',
    'command.explore':'Explorer', 'command.patrol':'Patrouiller', 'command.automate':'Automatiser',
    'command.optimize_food':'Optimiser la nourriture', 'command.optimize_production':'Optimiser la production',
    'command.optimize_gold':'Optimiser l’or', 'command.optimize_balanced':'Tout équilibrer',
    'command.clear_backlog':'Vider la file', 'command.select_all':'Tout sélectionner',
    'command.select_all_title':'Sélectionner toutes les unités militaires sur cette case',
    'production.none_selected':'Aucune production', 'production.backlog':'File :',
    'production.backlog_empty':'File : vide', 'production.blocked_money':'Production bloquée : trésor négatif',
    'production.turns':'{count} tours', 'production.status':'{name} ({turns} tours)',
    'production.paused_status':'{name} (en pause : P=0)',
    'production.city_economy':' Pop:{population} N:{food} P:{production} O:{money} Cons:{consumption} Croiss:{growth}',
    'production.focus':' Priorité : {focus}', 'production.current_suffix':' (en cours)',
    'production.option':'{name} ({cost}) {attack}/{defense}/{speed} | Coûts F:{food} G:{gold}',
    'unit.settlers':'Colons', 'unit.worker':'Ouvrier', 'unit.explorer':'Explorateur', 'unit.warrior':'Guerrier',
    'unit.slinger':'Frondeur', 'unit.archer':'Archer', 'unit.spearman':'Lancier', 'unit.horseman':'Cavalier',
    'unit.chariot':'Char', 'unit.elephant':'Éléphant', 'unit.catapult':'Catapulte', 'unit.trebuchet':'Trébuchet',
    'unit.galley':'Galère', 'unit.galleon':'Galion', 'unit.workboat':'Bateau-atelier', 'unit.frigate':'Frégate',
    'unit.knight':'Chevalier', 'unit.pikeman':'Piquier', 'unit.longbow':'Archer long', 'unit.fencer':'Bretteur',
    'unit.swordsman':'Épéiste', 'unit.trireme':'Trirème', 'unit.city':'Ville',
    'unit.destroyed_city':'Ville détruite', 'unit.generic':'Unité', 'unit.city_badge':'VILLE',
    'unit.units_count':'Unités ({count})', 'unit.units_at':'Unités en {i}, {j}',
    'unit.features':'{attack}/{defense}/{speed}', 'unit.selected_military':'Unités militaires sélectionnées : {count}',
    'unit.id':'ID unité : {id}', 'unit.pending':'en attente',
    'terrain.water':'Eau', 'terrain.sand':'Sable', 'terrain.grass':'Prairie', 'terrain.snow':'Neige',
    'terrain.hills':'Collines', 'terrain.rocks':'Rochers', 'terrain.forest':'Forêt',
    'terrain.grasswater':'Prairie humide', 'terrain.unknown':'Inconnu',
    'tile.defence':'Défense', 'tile.base':'Base', 'tile.resource':'Ressource', 'tile.current':'Actuel',
    'tile.suggested':'Conseillé', 'tile.after':'Après',
    'tile.income':'Nourriture {food} / Boucliers {production} / Or {gold}',
    'cost.unit_upkeep':'Entretien des unités', 'cost.city_balances':'Bilans des villes par tour',
    'cost.city':'Ville', 'cost.population':'Pop.', 'cost.producing':'Production',
    'cost.balance_food_production_gold':'Solde N/P/O', 'cost.no_cities':'Aucune ville',
    'cost.improvement_upkeep':'Entretien des aménagements',
    'cost.each_food_gold':'Chaque N/O', 'cost.total_food_gold':'Total N/O',
    'cost.each_food_production_gold':'Chaque N/P/O', 'cost.total_food_production_gold':'Total N/P/O',
    'cost.no_units':'Aucune unité',
    'civilization.coat_title':'Armoiries de {name}', 'civilization.own_suffix':' ({you})',
    'civilization.units_cities':'Unités : {units} | Villes : {cities}',
    'civilization.food_gold':'Nourriture : {food} | Or : {gold}',
    'civilization.results':'Tuées : {killed} | Occupées : {occupied} | Détruites : {destroyed}',
    'civilization.relation_to_you':'Relation avec vous : {relation}',
    'relation.friend':'Ami', 'relation.enemy':'Ennemi', 'relation.neutral':'Neutre', 'relation.self':'Nous',
    'technology.science_rate':'Science : {rate}%', 'technology.research_unavailable':'Recherche indisponible',
    'technology.status':'Technologie : {name} {progress}/{cost}',
    'technology.all_discovered':'Toutes les technologies sont découvertes',
    'technology.Mining':'Exploitation minière', 'technology.Pottery':'Poterie',
    'technology.Animal Husbandry':'Élevage', 'technology.Sailing':'Navigation à voile',
    'technology.Masonry':'Maçonnerie', 'technology.Bronze Working':'Travail du bronze',
    'technology.Irrigation':'Irrigation', 'technology.Writing':'Écriture', 'technology.Archery':'Tir à l’arc',
    'technology.Wheel':'Roue', 'technology.Astronomy':'Astronomie', 'technology.Currency':'Monnaie',
    'technology.Horseback Riding':'Équitation', 'technology.Iron Working':'Travail du fer',
    'technology.Shipbuilding':'Construction navale', 'technology.Mathematics':'Mathématiques',
    'technology.Navigation':'Navigation', 'technology.Construction':'Construction', 'technology.Engineering':'Ingénierie',
    'resource.bananas':'Bananes', 'resource.cattle':'Bétail', 'resource.copper':'Cuivre', 'resource.crabs':'Crabes',
    'resource.deer':'Cerfs', 'resource.fish':'Poisson', 'resource.rice':'Riz', 'resource.sheep':'Moutons',
    'resource.stone':'Pierre', 'resource.wheat':'Blé', 'resource.amber':'Ambre', 'resource.citrus':'Agrumes',
    'resource.cotton':'Coton', 'resource.dyes':'Teintures', 'resource.diamonds':'Diamants', 'resource.furs':'Fourrures',
    'resource.gypsum':'Gypse', 'resource.honey':'Miel', 'resource.incense':'Encens', 'resource.ivory':'Ivoire',
    'resource.marble':'Marbre', 'resource.olives':'Olives', 'resource.pearls':'Perles', 'resource.salt':'Sel',
    'resource.silk':'Soie', 'resource.silver':'Argent', 'resource.spices':'Épices', 'resource.sugar':'Sucre',
    'resource.tea':'Thé', 'resource.turtles':'Tortues', 'resource.whales':'Baleines', 'resource.wine':'Vin',
    'resource.horses':'Chevaux', 'resource.iron':'Fer', 'resource.gold':'Or', 'resource.gems':'Gemmes',
    'turn.end_ai_user':'Fin du tour IA {id}', 'turn.end_user':'Fin du tour du joueur {id}',
    'auth.login_or_email':'Identifiant ou e-mail', 'auth.login':'Connexion', 'auth.email_optional':'E-mail (facultatif)',
    'auth.password':'Mot de passe', 'auth.remember_me':'Se souvenir de moi', 'auth.register':'S’inscrire',
    'auth.register_heading':'Inscription du joueur', 'auth.register_new':'Inscrire un nouveau joueur',
    'auth.return_login':'Retour à la connexion', 'auth.login_failed':'Échec de la connexion.',
    'auth.registration_failed':'Échec de l’inscription.',
    'auth.cookie_rejected':'Le navigateur a refusé le cookie de session. Autorisez les cookies pour ce site.',
    'auth.session_expired':'Votre session a expiré. Reconnectez-vous.',
    'auth.invalid_session':'Votre session est invalide. Reconnectez-vous.',
    'auth.authentication_required':'Connectez-vous pour continuer.', 'auth.account_unavailable':'Ce compte est indisponible.',
    'message.disband_pending':'L’unité #{id} sera dissoute à la fin du tour.',
    'message.unit_destroyed_funds':'L’unité « {name} » est détruite faute de fonds.',
    'message.worker_command_unavailable':'{command} n’est pas disponible pour l’ouvrier #{id} sur cette case.',
    'message.preparing_ai':'Préparation du joueur IA {id}...', 'message.ai_not_ready':'Joueur IA {id} non prêt'
});
