'use strict';

registerVocabularyPack('IT', {
    'app.login_title':'Accesso ad AI Civilization', 'app.register_title':'Registrazione ad AI Civilization',
    'common.none':'Nessuno', 'common.open':'Scoperta', 'common.clear':'Cancella', 'common.close':'Chiudi',
    'common.waiting':'In attesa', 'common.overall':'Totale', 'common.type':'Tipo', 'common.count':'Quantità',
    'common.health':'Salute', 'common.you':'tu',
    'hud.food_storage':'Scorta di cibo', 'hud.gold_storage':'Tesoro', 'hud.end_turn':'Fine turno',
    'hud.turn_seconds':'{action} ({seconds}s)', 'hud.options':'Opzioni', 'hud.log_out':'Esci',
    'hud.logging_out':'Uscita...', 'hud.respawn':'Rigenera', 'hud.back_to_game':'Torna al gioco',
    'hud.respawn_prompt':'Fai clic sulla minimappa per scegliere il punto di rigenerazione',
    'hud.respawning':'Rigenerazione della civiltà...',
    'menu.action_options':'Azioni:', 'menu.technology':'Tecnologia', 'menu.politics':'Politica',
    'menu.finance':'Finanze', 'menu.trade':'Commercio', 'menu.ai_console':'Console IA',
    'menu.ai_console_status':'Decisioni del modello e ordini applicati', 'menu.costs':'Costi',
    'menu.turn_costs':'Costi del turno', 'menu.civilizations':'Civiltà', 'menu.civs':'Civ',
    'command.goto':'Vai a', 'command.fortificate':'Fortifica', 'command.fortification':'Fortificazione',
    'command.road':'Strada', 'command.road_to':'Strada verso', 'command.pasture':'Pascolo',
    'command.farm':'Fattoria', 'command.plantation':'Piantagione', 'command.camp':'Accampamento',
    'command.fishing_boats':'Barche da pesca', 'command.network':'Reti', 'command.quarry':'Cava',
    'command.winery':'Cantina', 'command.cottage':'Casale', 'command.workshop':'Officina',
    'command.mine':'Miniera', 'command.disband':'Sciogli', 'command.wait':'Attendi',
    'command.irrigate':'Irriga', 'command.chop_forest':'Taglia la foresta', 'command.build_city':'Fonda città',
    'command.explore':'Esplora', 'command.patrol':'Pattuglia', 'command.automate':'Automatizza',
    'command.optimize_food':'Ottimizza cibo', 'command.optimize_production':'Ottimizza produzione',
    'command.optimize_gold':'Ottimizza oro', 'command.optimize_balanced':'Bilancia tutto',
    'command.clear_backlog':'Svuota coda', 'command.select_all':'Seleziona tutto',
    'command.select_all_title':'Seleziona tutte le unità militari su questa casella',
    'production.none_selected':'Nessuna produzione', 'production.backlog':'Coda:',
    'production.backlog_empty':'Coda: vuota', 'production.blocked_money':'Produzione bloccata: conto negativo',
    'production.turns':'{count} turni', 'production.status':'{name} ({turns} turni)',
    'production.paused_status':'{name} (in pausa: P=0)',
    'production.city_economy':' Pop:{population} C:{food} P:{production} O:{money} Cons:{consumption} Cres:{growth}',
    'production.focus':' Priorità: {focus}', 'production.current_suffix':' (attuale)',
    'production.option':'{name} ({cost}) {attack}/{defense}/{speed} | Costi F:{food} G:{gold}',
    'unit.settlers':'Coloni', 'unit.worker':'Lavoratore', 'unit.explorer':'Esploratore', 'unit.warrior':'Guerriero',
    'unit.slinger':'Fromboliere', 'unit.archer':'Arciere', 'unit.spearman':'Lanciere', 'unit.horseman':'Cavaliere',
    'unit.chariot':'Carro', 'unit.elephant':'Elefante', 'unit.catapult':'Catapulta', 'unit.trebuchet':'Trabucco',
    'unit.galley':'Galea', 'unit.galleon':'Galeone', 'unit.workboat':'Barca da lavoro', 'unit.frigate':'Fregata',
    'unit.knight':'Cavaliere corazzato', 'unit.pikeman':'Picchiere', 'unit.longbow':'Arco lungo',
    'unit.fencer':'Schermidore', 'unit.swordsman':'Spadaccino', 'unit.trireme':'Trireme', 'unit.city':'Città',
    'unit.destroyed_city':'Città distrutta', 'unit.generic':'Unità', 'unit.city_badge':'CITTÀ',
    'unit.units_count':'Unità ({count})', 'unit.units_at':'Unità a {i}, {j}',
    'unit.features':'{attack}/{defense}/{speed}',
    'unit.selected_military':'Unità militari selezionate: {count}', 'unit.id':'ID unità: {id}',
    'unit.pending':'in attesa',
    'terrain.water':'Acqua', 'terrain.sand':'Sabbia', 'terrain.grass':'Prateria', 'terrain.snow':'Neve',
    'terrain.hills':'Colline', 'terrain.rocks':'Rocce', 'terrain.forest':'Foresta',
    'terrain.grasswater':'Prateria con acqua', 'terrain.unknown':'Sconosciuto',
    'tile.defence':'Difesa', 'tile.base':'Base', 'tile.resource':'Risorsa', 'tile.current':'Attuale',
    'tile.suggested':'Suggerito', 'tile.after':'Dopo',
    'tile.income':'Cibo {food} / Scudi {production} / Oro {gold}',
    'cost.unit_upkeep':'Mantenimento unità', 'cost.city_balances':'Bilanci delle città per turno',
    'cost.city':'Città', 'cost.population':'Pop.', 'cost.producing':'Produzione',
    'cost.balance_food_production_gold':'Bilancio C/P/O', 'cost.no_cities':'Nessuna città',
    'cost.improvement_upkeep':'Mantenimento miglioramenti',
    'cost.each_food_gold':'Ogni C/O', 'cost.total_food_gold':'Totale C/O',
    'cost.each_food_production_gold':'Ogni C/P/O', 'cost.total_food_production_gold':'Totale C/P/O',
    'cost.no_units':'Nessuna unità',
    'civilization.coat_title':'Stemma di {name}', 'civilization.own_suffix':' ({you})',
    'civilization.units_cities':'Unità: {units} | Città: {cities}',
    'civilization.food_gold':'Cibo: {food} | Oro: {gold}',
    'civilization.results':'Uccise: {killed} | Occupate: {occupied} | Distrutte: {destroyed}',
    'civilization.relation_to_you':'Relazione con te: {relation}',
    'relation.friend':'Amico', 'relation.enemy':'Nemico', 'relation.neutral':'Neutrale', 'relation.self':'Propria',
    'technology.science_rate':'Scienza: {rate}%', 'technology.research_unavailable':'Ricerca non disponibile',
    'technology.status':'Tecnologia: {name} {progress}/{cost}',
    'technology.all_discovered':'Tutte le tecnologie scoperte',
    'technology.Mining':'Estrazione mineraria', 'technology.Pottery':'Ceramica',
    'technology.Animal Husbandry':'Allevamento', 'technology.Sailing':'Vela', 'technology.Masonry':'Muratura',
    'technology.Bronze Working':'Lavorazione del bronzo', 'technology.Irrigation':'Irrigazione',
    'technology.Writing':'Scrittura', 'technology.Archery':'Tiro con l’arco', 'technology.Wheel':'Ruota',
    'technology.Astronomy':'Astronomia', 'technology.Currency':'Valuta', 'technology.Horseback Riding':'Equitazione',
    'technology.Iron Working':'Lavorazione del ferro', 'technology.Shipbuilding':'Costruzione navale',
    'technology.Mathematics':'Matematica', 'technology.Navigation':'Navigazione',
    'technology.Construction':'Costruzione', 'technology.Engineering':'Ingegneria',
    'resource.bananas':'Banane', 'resource.cattle':'Bestiame', 'resource.copper':'Rame', 'resource.crabs':'Granchi',
    'resource.deer':'Cervi', 'resource.fish':'Pesce', 'resource.rice':'Riso', 'resource.sheep':'Pecore',
    'resource.stone':'Pietra', 'resource.wheat':'Grano', 'resource.amber':'Ambra', 'resource.citrus':'Agrumi',
    'resource.cotton':'Cotone', 'resource.dyes':'Coloranti', 'resource.diamonds':'Diamanti', 'resource.furs':'Pellicce',
    'resource.gypsum':'Gesso', 'resource.honey':'Miele', 'resource.incense':'Incenso', 'resource.ivory':'Avorio',
    'resource.marble':'Marmo', 'resource.olives':'Olive', 'resource.pearls':'Perle', 'resource.salt':'Sale',
    'resource.silk':'Seta', 'resource.silver':'Argento', 'resource.spices':'Spezie', 'resource.sugar':'Zucchero',
    'resource.tea':'Tè', 'resource.turtles':'Tartarughe', 'resource.whales':'Balene', 'resource.wine':'Vino',
    'resource.horses':'Cavalli', 'resource.iron':'Ferro', 'resource.gold':'Oro', 'resource.gems':'Gemme',
    'turn.end_ai_user':'Fine turno IA {id}', 'turn.end_user':'Fine turno giocatore {id}',
    'auth.login_or_email':'Nome utente o e-mail', 'auth.login':'Accedi', 'auth.email_optional':'E-mail (facoltativa)',
    'auth.password':'Password', 'auth.remember_me':'Ricordami', 'auth.register':'Registrati',
    'auth.register_heading':'Registra giocatore', 'auth.register_new':'Registra un nuovo giocatore',
    'auth.return_login':'Torna all’accesso', 'auth.login_failed':'Accesso non riuscito.',
    'auth.registration_failed':'Registrazione non riuscita.',
    'auth.cookie_rejected':'Il browser ha rifiutato il cookie di sessione. Abilita i cookie per questo sito.',
    'auth.session_expired':'La sessione è scaduta. Accedi di nuovo.',
    'auth.invalid_session':'La sessione non è valida. Accedi di nuovo.',
    'auth.authentication_required':'Accedi per continuare.', 'auth.account_unavailable':'Questo account non è disponibile.',
    'message.disband_pending':'L’unità #{id} verrà sciolta alla fine del turno.',
    'message.unit_destroyed_funds':'L’unità «{name}» è stata distrutta per mancanza di fondi.',
    'message.worker_command_unavailable':'{command} non è disponibile per il lavoratore #{id} su questa casella.',
    'message.preparing_ai':'Preparazione giocatore IA {id}...', 'message.ai_not_ready':'Giocatore IA {id} non pronto'
});
