'use strict';

registerVocabularyPack('JP', {
    'app.login_title':'AI Civilization ログイン', 'app.register_title':'AI Civilization 登録',
    'common.none':'なし', 'common.open':'研究済み', 'common.clear':'消去', 'common.close':'閉じる',
    'common.waiting':'待機中', 'common.overall':'合計', 'common.type':'種類', 'common.count':'数',
    'common.health':'体力', 'common.you':'あなた',
    'hud.food_storage':'食料備蓄', 'hud.gold_storage':'国庫', 'hud.end_turn':'ターン終了',
    'hud.turn_seconds':'{action}（{seconds}秒）', 'hud.options':'オプション', 'hud.log_out':'ログアウト',
    'hud.logging_out':'ログアウト中...', 'hud.respawn':'再出現', 'hud.back_to_game':'ゲームに戻る',
    'hud.respawn_prompt':'ミニマップをクリックして再出現地点を選択', 'hud.respawning':'文明を再出現中...',
    'menu.action_options':'行動：', 'menu.technology':'技術', 'menu.politics':'政治', 'menu.finance':'財政',
    'menu.trade':'交易', 'menu.ai_console':'AI コンソール', 'menu.ai_console_status':'モデルの判断と適用された命令',
    'menu.costs':'費用', 'menu.turn_costs':'ターン費用', 'menu.civilizations':'文明', 'menu.civs':'文明',
    'command.goto':'移動', 'command.fortificate':'防御態勢', 'command.fortification':'要塞建設',
    'command.road':'道路', 'command.road_to':'道路を敷く', 'command.pasture':'牧場', 'command.farm':'農場',
    'command.plantation':'プランテーション', 'command.camp':'野営地', 'command.fishing_boats':'漁船',
    'command.network':'漁網', 'command.quarry':'採石場', 'command.winery':'ワイナリー',
    'command.cottage':'小屋', 'command.workshop':'工房', 'command.mine':'鉱山',
    'command.disband':'解散', 'command.wait':'待機', 'command.irrigate':'灌漑',
    'command.chop_forest':'森林伐採', 'command.build_city':'都市建設', 'command.explore':'探索',
    'command.patrol':'哨戒', 'command.automate':'自動化', 'command.optimize_food':'食料を優先',
    'command.optimize_production':'生産を優先', 'command.optimize_gold':'ゴールドを優先',
    'command.optimize_balanced':'均等に最適化', 'command.clear_backlog':'キューを消去',
    'command.select_all':'すべて選択', 'command.select_all_title':'このタイルの全軍事ユニットを選択',
    'production.none_selected':'生産なし', 'production.backlog':'生産キュー：', 'production.backlog_empty':'生産キュー：空',
    'production.blocked_money':'生産停止：国庫がマイナスです', 'production.turns':'{count} ターン',
    'production.status':'{name}（{turns} ターン）',
    'production.paused_status':'{name}（一時停止：生産=0）',
    'production.city_economy':' 人口:{population} 食:{food} 生:{production} 金:{money} 消費:{consumption} 成長:{growth}',
    'production.focus':' 重点：{focus}', 'production.current_suffix':'（生産中）',
    'production.option':'{name}（{cost}）{attack}/{defense}/{speed} | 維持費 F:{food} G:{gold}',
    'unit.settlers':'開拓者', 'unit.worker':'労働者', 'unit.explorer':'探検家', 'unit.warrior':'戦士',
    'unit.slinger':'投石兵', 'unit.archer':'弓兵', 'unit.spearman':'槍兵', 'unit.horseman':'騎兵',
    'unit.chariot':'戦車', 'unit.elephant':'戦象', 'unit.catapult':'カタパルト', 'unit.trebuchet':'トレビュシェット',
    'unit.galley':'ガレー船', 'unit.galleon':'ガレオン船', 'unit.workboat':'作業船', 'unit.frigate':'フリゲート',
    'unit.knight':'騎士', 'unit.pikeman':'長槍兵', 'unit.longbow':'長弓兵', 'unit.fencer':'剣術士',
    'unit.swordsman':'剣士', 'unit.trireme':'三段櫂船', 'unit.city':'都市',
    'unit.destroyed_city':'廃墟都市', 'unit.generic':'ユニット', 'unit.city_badge':'都市',
    'unit.units_count':'ユニット（{count}）', 'unit.units_at':'{i}, {j} のユニット',
    'unit.features':'{attack}/{defense}/{speed}', 'unit.selected_military':'選択中の軍事ユニット：{count}',
    'unit.id':'ユニット ID：{id}', 'unit.pending':'保留中',
    'terrain.water':'水域', 'terrain.sand':'砂地', 'terrain.grass':'草原', 'terrain.snow':'雪原',
    'terrain.hills':'丘陵', 'terrain.rocks':'岩場', 'terrain.forest':'森林',
    'terrain.grasswater':'水のある草原', 'terrain.unknown':'不明',
    'tile.defence':'防御', 'tile.base':'基本', 'tile.resource':'資源', 'tile.current':'現在',
    'tile.suggested':'推奨', 'tile.after':'建設後', 'tile.income':'食料 {food} / 生産 {production} / ゴールド {gold}',
    'cost.unit_upkeep':'ユニット維持費', 'cost.city_balances':'都市のターン収支',
    'cost.city':'都市', 'cost.population':'人口', 'cost.producing':'生産',
    'cost.balance_food_production_gold':'収支 食/生/金', 'cost.no_cities':'都市なし',
    'cost.improvement_upkeep':'改善維持費',
    'cost.each_food_gold':'1つ当たり 食/金', 'cost.total_food_gold':'合計 食/金',
    'cost.each_food_production_gold':'1つ当たり 食/生/金', 'cost.total_food_production_gold':'合計 食/生/金',
    'cost.no_units':'ユニットなし',
    'civilization.coat_title':'{name} の紋章', 'civilization.own_suffix':'（{you}）',
    'civilization.units_cities':'ユニット：{units} | 都市：{cities}',
    'civilization.food_gold':'食料：{food} | ゴールド：{gold}',
    'civilization.results':'撃破：{killed} | 占領：{occupied} | 破壊：{destroyed}',
    'civilization.relation_to_you':'あなたとの関係：{relation}',
    'relation.friend':'友好', 'relation.enemy':'敵対', 'relation.neutral':'中立', 'relation.self':'自国',
    'technology.science_rate':'科学：{rate}%', 'technology.research_unavailable':'研究できません',
    'technology.status':'技術：{name} {progress}/{cost}', 'technology.all_discovered':'すべての技術を研究済み',
    'technology.Mining':'採鉱', 'technology.Pottery':'陶器', 'technology.Animal Husbandry':'畜産',
    'technology.Sailing':'帆走', 'technology.Masonry':'石工術', 'technology.Bronze Working':'青銅器',
    'technology.Irrigation':'灌漑', 'technology.Writing':'筆記', 'technology.Archery':'弓術',
    'technology.Wheel':'車輪', 'technology.Astronomy':'天文学', 'technology.Currency':'通貨',
    'technology.Horseback Riding':'騎乗', 'technology.Iron Working':'鉄器', 'technology.Shipbuilding':'造船',
    'technology.Mathematics':'数学', 'technology.Navigation':'航海術',
    'technology.Construction':'建設', 'technology.Engineering':'工学',
    'resource.bananas':'バナナ', 'resource.cattle':'牛', 'resource.copper':'銅', 'resource.crabs':'カニ',
    'resource.deer':'鹿', 'resource.fish':'魚', 'resource.rice':'米', 'resource.sheep':'羊',
    'resource.stone':'石材', 'resource.wheat':'小麦', 'resource.amber':'琥珀', 'resource.citrus':'柑橘',
    'resource.cotton':'綿花', 'resource.dyes':'染料', 'resource.diamonds':'ダイヤモンド', 'resource.furs':'毛皮',
    'resource.gypsum':'石膏', 'resource.honey':'蜂蜜', 'resource.incense':'香料', 'resource.ivory':'象牙',
    'resource.marble':'大理石', 'resource.olives':'オリーブ', 'resource.pearls':'真珠', 'resource.salt':'塩',
    'resource.silk':'絹', 'resource.silver':'銀', 'resource.spices':'香辛料', 'resource.sugar':'砂糖',
    'resource.tea':'茶', 'resource.turtles':'ウミガメ', 'resource.whales':'クジラ', 'resource.wine':'ワイン',
    'resource.horses':'馬', 'resource.iron':'鉄', 'resource.gold':'金', 'resource.gems':'宝石',
    'turn.end_ai_user':'AI プレイヤー {id} のターン終了', 'turn.end_user':'プレイヤー {id} のターン終了',
    'auth.login_or_email':'ログイン名またはメール', 'auth.login':'ログイン', 'auth.email_optional':'メール（任意）',
    'auth.password':'パスワード', 'auth.remember_me':'ログイン情報を保存', 'auth.register':'登録',
    'auth.register_heading':'プレイヤー登録', 'auth.register_new':'新しいプレイヤーを登録',
    'auth.return_login':'ログインに戻る', 'auth.login_failed':'ログインに失敗しました。',
    'auth.registration_failed':'登録に失敗しました。',
    'auth.cookie_rejected':'ブラウザがセッション Cookie を拒否しました。このサイトの Cookie を許可してください。',
    'auth.session_expired':'セッションの期限が切れました。再度ログインしてください。',
    'auth.invalid_session':'セッションが無効です。再度ログインしてください。',
    'auth.authentication_required':'続行するにはログインしてください。', 'auth.account_unavailable':'このアカウントは利用できません。',
    'message.disband_pending':'ユニット #{id} はターン終了時に解散します。',
    'message.unit_destroyed_funds':'資金不足によりユニット「{name}」が解散しました。',
    'message.worker_command_unavailable':'労働者 #{id} はこのタイルで「{command}」を実行できません。',
    'message.preparing_ai':'AI プレイヤー {id} を準備中...', 'message.ai_not_ready':'AI プレイヤー {id} は準備できていません'
});
