'use strict';

registerVocabularyPack('SP', {
    'app.login_title':'Inicio de sesión de AI Civilization', 'app.register_title':'Registro de AI Civilization',
    'common.none':'Ninguno', 'common.open':'Descubierta', 'common.clear':'Limpiar', 'common.close':'Cerrar',
    'common.waiting':'Esperando', 'common.overall':'Total', 'common.type':'Tipo', 'common.count':'Cantidad',
    'common.health':'Salud', 'common.you':'tú',
    'hud.food_storage':'Reserva de alimentos', 'hud.gold_storage':'Tesoro', 'hud.end_turn':'Terminar turno',
    'hud.turn_seconds':'{action} ({seconds}s)', 'hud.options':'Opciones', 'hud.log_out':'Cerrar sesión',
    'hud.logging_out':'Cerrando sesión...', 'hud.respawn':'Reaparecer', 'hud.back_to_game':'Volver al juego',
    'hud.respawn_prompt':'Haz clic en el minimapa para elegir el punto de reaparición',
    'hud.respawning':'Reapareciendo civilización...',
    'menu.action_options':'Acciones:', 'menu.technology':'Tecnología', 'menu.politics':'Política',
    'menu.finance':'Finanzas', 'menu.trade':'Comercio', 'menu.ai_console':'Consola de IA',
    'menu.ai_console_status':'Decisiones del modelo y órdenes aplicadas', 'menu.costs':'Costes',
    'menu.turn_costs':'Costes del turno', 'menu.civilizations':'Civilizaciones', 'menu.civs':'Civs',
    'command.goto':'Ir a', 'command.fortificate':'Fortificar', 'command.fortification':'Fortificación',
    'command.road':'Camino', 'command.road_to':'Camino hasta', 'command.pasture':'Pastizal',
    'command.farm':'Granja', 'command.plantation':'Plantación', 'command.camp':'Campamento',
    'command.fishing_boats':'Barcos pesqueros', 'command.network':'Redes', 'command.quarry':'Cantera',
    'command.winery':'Bodega', 'command.cottage':'Casa de campo', 'command.workshop':'Taller',
    'command.mine':'Mina', 'command.disband':'Disolver', 'command.wait':'Esperar',
    'command.irrigate':'Irrigar', 'command.chop_forest':'Talar bosque', 'command.build_city':'Fundar ciudad',
    'command.explore':'Explorar', 'command.patrol':'Patrullar', 'command.automate':'Automatizar',
    'command.optimize_food':'Optimizar alimentos', 'command.optimize_production':'Optimizar producción',
    'command.optimize_gold':'Optimizar oro', 'command.optimize_balanced':'Equilibrar todo',
    'command.clear_backlog':'Vaciar cola', 'command.select_all':'Seleccionar todo',
    'command.select_all_title':'Seleccionar todas las unidades militares de esta casilla',
    'production.none_selected':'Sin producción', 'production.backlog':'Cola:', 'production.backlog_empty':'Cola: vacía',
    'production.blocked_money':'Producción bloqueada: cuenta negativa', 'production.turns':'{count} turnos',
    'production.status':'{name} ({turns} turnos)',
    'production.paused_status':'{name} (pausado: P=0)',
    'production.city_economy':' Pob:{population} A:{food} P:{production} O:{money} Cons:{consumption} Crec:{growth}',
    'production.focus':' Prioridad: {focus}', 'production.current_suffix':' (actual)',
    'production.option':'{name} ({cost}) {attack}/{defense}/{speed} | Costes F:{food} G:{gold}',
    'unit.settlers':'Colonos', 'unit.worker':'Trabajador', 'unit.explorer':'Explorador', 'unit.warrior':'Guerrero',
    'unit.slinger':'Hondero', 'unit.archer':'Arquero', 'unit.spearman':'Lancero', 'unit.horseman':'Jinete',
    'unit.chariot':'Carro', 'unit.elephant':'Elefante', 'unit.catapult':'Catapulta', 'unit.trebuchet':'Trabuquete',
    'unit.galley':'Galera', 'unit.galleon':'Galeón', 'unit.workboat':'Barco de trabajo', 'unit.frigate':'Fragata',
    'unit.knight':'Caballero', 'unit.pikeman':'Piquero', 'unit.longbow':'Arquero largo', 'unit.fencer':'Esgrimista',
    'unit.swordsman':'Espadachín', 'unit.trireme':'Trirreme', 'unit.city':'Ciudad',
    'unit.destroyed_city':'Ciudad destruida', 'unit.generic':'Unidad', 'unit.city_badge':'CIUDAD',
    'unit.units_count':'Unidades ({count})', 'unit.units_at':'Unidades en {i}, {j}',
    'unit.features':'{attack}/{defense}/{speed}',
    'unit.selected_military':'Unidades militares seleccionadas: {count}', 'unit.id':'ID de unidad: {id}',
    'unit.pending':'pendiente',
    'terrain.water':'Agua', 'terrain.sand':'Arena', 'terrain.grass':'Pradera', 'terrain.snow':'Nieve',
    'terrain.hills':'Colinas', 'terrain.mountains':'Montañas', 'terrain.forest':'Bosque',
    'terrain.grasswater':'Pradera con agua', 'terrain.unknown':'Desconocido',
    'tile.defence':'Defensa', 'tile.base':'Base', 'tile.resource':'Recurso', 'tile.current':'Actual',
    'tile.suggested':'Sugerido', 'tile.after':'Después',
    'tile.income':'Alimentos {food} / Escudos {production} / Oro {gold}',
    'cost.unit_upkeep':'Mantenimiento de unidades', 'cost.city_balances':'Balance de ciudades por turno',
    'cost.city':'Ciudad', 'cost.population':'Pob.', 'cost.producing':'Producción',
    'cost.balance_food_production_gold':'Balance A/P/O', 'cost.no_cities':'Sin ciudades',
    'cost.improvement_upkeep':'Mantenimiento de mejoras',
    'cost.each_food_gold':'Cada A/O', 'cost.total_food_gold':'Total A/O',
    'cost.each_food_production_gold':'Cada A/P/O', 'cost.total_food_production_gold':'Total A/P/O',
    'cost.no_units':'Sin unidades',
    'civilization.coat_title':'Escudo de {name}', 'civilization.own_suffix':' ({you})',
    'civilization.units_cities':'Unidades: {units} | Ciudades: {cities}',
    'civilization.food_gold':'Alimentos: {food} | Oro: {gold}',
    'civilization.results':'Muertas: {killed} | Ocupadas: {occupied} | Destruidas: {destroyed}',
    'civilization.relation_to_you':'Relación contigo: {relation}',
    'relation.friend':'Amigo', 'relation.enemy':'Enemigo', 'relation.neutral':'Neutral', 'relation.self':'Propia',
    'technology.science_rate':'Ciencia: {rate}%', 'technology.research_unavailable':'Investigación no disponible',
    'technology.status':'Tecnología: {name} {progress}/{cost}',
    'technology.all_discovered':'Todas las tecnologías descubiertas',
    'technology.Mining':'Minería', 'technology.Pottery':'Cerámica', 'technology.Animal Husbandry':'Ganadería',
    'technology.Sailing':'Navegación a vela', 'technology.Masonry':'Mampostería',
    'technology.Bronze Working':'Trabajo del bronce', 'technology.Irrigation':'Irrigación',
    'technology.Writing':'Escritura', 'technology.Archery':'Tiro con arco', 'technology.Wheel':'Rueda',
    'technology.Astronomy':'Astronomía', 'technology.Currency':'Moneda', 'technology.Horseback Riding':'Equitación',
    'technology.Iron Working':'Trabajo del hierro', 'technology.Shipbuilding':'Construcción naval',
    'technology.Mathematics':'Matemáticas', 'technology.Navigation':'Navegación',
    'technology.Construction':'Construcción', 'technology.Engineering':'Ingeniería',
    'resource.bananas':'Plátanos', 'resource.cattle':'Ganado', 'resource.copper':'Cobre', 'resource.crabs':'Cangrejos',
    'resource.deer':'Ciervos', 'resource.fish':'Pescado', 'resource.rice':'Arroz', 'resource.sheep':'Ovejas',
    'resource.stone':'Piedra', 'resource.wheat':'Trigo', 'resource.amber':'Ámbar', 'resource.citrus':'Cítricos',
    'resource.cotton':'Algodón', 'resource.dyes':'Tintes', 'resource.diamonds':'Diamantes', 'resource.furs':'Pieles',
    'resource.gypsum':'Yeso', 'resource.honey':'Miel', 'resource.incense':'Incienso', 'resource.ivory':'Marfil',
    'resource.marble':'Mármol', 'resource.olives':'Aceitunas', 'resource.pearls':'Perlas', 'resource.salt':'Sal',
    'resource.silk':'Seda', 'resource.silver':'Plata', 'resource.spices':'Especias', 'resource.sugar':'Azúcar',
    'resource.tea':'Té', 'resource.turtles':'Tortugas', 'resource.whales':'Ballenas', 'resource.wine':'Vino',
    'resource.horses':'Caballos', 'resource.iron':'Hierro', 'resource.gold':'Oro', 'resource.gems':'Gemas',
    'turn.end_ai_user':'Terminar turno de IA {id}', 'turn.end_user':'Terminar turno del jugador {id}',
    'auth.login_or_email':'Usuario o correo', 'auth.login':'Iniciar sesión', 'auth.email_optional':'Correo (opcional)',
    'auth.password':'Contraseña', 'auth.remember_me':'Recordarme', 'auth.register':'Registrarse',
    'auth.register_heading':'Registrar jugador', 'auth.register_new':'Registrar nuevo jugador',
    'auth.return_login':'Volver al inicio de sesión', 'auth.login_failed':'Error de inicio de sesión.',
    'auth.registration_failed':'Error de registro.',
    'auth.cookie_rejected':'El navegador rechazó la cookie de sesión. Habilita las cookies para este sitio.',
    'auth.session_expired':'Tu sesión expiró. Inicia sesión de nuevo.',
    'auth.invalid_session':'Tu sesión no es válida. Inicia sesión de nuevo.',
    'auth.authentication_required':'Inicia sesión para continuar.', 'auth.account_unavailable':'Esta cuenta no está disponible.',
    'message.disband_pending':'La unidad #{id} se disolverá al terminar el turno.',
    'message.unit_destroyed_funds':'La unidad «{name}» fue destruida por falta de fondos.',
    'message.worker_command_unavailable':'{command} no está disponible para el trabajador #{id} en esta casilla.',
    'message.preparing_ai':'Preparando jugador IA {id}...', 'message.ai_not_ready':'El jugador IA {id} no está listo'
});
