'use strict';

registerVocabularyPack('RU', {
    'app.login_title':'Вход в AI Civilization', 'app.register_title':'Регистрация в AI Civilization',
    'common.none':'Нет', 'common.open':'Открыто', 'common.clear':'Очистить', 'common.close':'Закрыть',
    'common.waiting':'Ожидание', 'common.overall':'Всего', 'common.type':'Тип', 'common.count':'Количество',
    'common.health':'Здоровье', 'common.you':'вы',
    'hud.food_storage':'Запас еды', 'hud.gold_storage':'Казна', 'hud.end_turn':'Завершить ход',
    'hud.turn_seconds':'{action} ({seconds}с)', 'hud.options':'Настройки', 'hud.log_out':'Выйти',
    'hud.logging_out':'Выход...', 'hud.respawn':'Возродиться', 'hud.back_to_game':'Вернуться в игру',
    'hud.respawn_prompt':'Щёлкните по миникарте, чтобы выбрать место возрождения',
    'hud.respawning':'Возрождение цивилизации...',
    'menu.action_options':'Действия:', 'menu.technology':'Технологии', 'menu.politics':'Политика',
    'menu.finance':'Финансы', 'menu.trade':'Торговля', 'menu.ai_console':'Консоль ИИ',
    'menu.ai_console_status':'Решения модели и выполненные приказы', 'menu.costs':'Расходы',
    'menu.turn_costs':'Расходы за ход', 'menu.civilizations':'Цивилизации', 'menu.civs':'Цивы',
    'command.goto':'Идти', 'command.fortificate':'Укрепиться', 'command.fortification':'Форт',
    'command.road':'Дорога', 'command.road_to':'Дорога до', 'command.pasture':'Пастбище',
    'command.farm':'Ферма', 'command.plantation':'Плантация', 'command.camp':'Лагерь',
    'command.fishing_boats':'Рыбацкие лодки', 'command.network':'Сети', 'command.quarry':'Каменоломня',
    'command.winery':'Винодельня', 'command.cottage':'Дом', 'command.workshop':'Мастерская',
    'command.mine':'Шахта', 'command.disband':'Распустить', 'command.wait':'Ждать',
    'command.irrigate':'Орошать', 'command.chop_forest':'Вырубить лес', 'command.build_city':'Основать город',
    'command.explore':'Исследовать', 'command.patrol':'Патрулировать', 'command.automate':'Автоматически',
    'command.optimize_food':'Больше еды', 'command.optimize_production':'Больше производства',
    'command.optimize_gold':'Больше золота', 'command.optimize_balanced':'Сбалансировать',
    'command.clear_backlog':'Очистить очередь', 'command.select_all':'Выбрать всех',
    'command.select_all_title':'Выбрать все военные отряды на этой клетке',
    'production.none_selected':'Ничего не производится', 'production.backlog':'Очередь:',
    'production.backlog_empty':'Очередь пуста', 'production.blocked_money':'Производство остановлено: отрицательная казна',
    'production.turns':'{count} ходов', 'production.status':'{name} ({turns} ходов)',
    'production.paused_status':'{name} (приостановлено: П=0)',
    'production.city_economy':' Нас:{population} Е:{food} П:{production} З:{money} Потр:{consumption} Рост:{growth}',
    'production.focus':' Приоритет: {focus}', 'production.current_suffix':' (сейчас)',
    'production.option':'{name} ({cost}) {attack}/{defense}/{speed} | Цена F:{food} G:{gold}',
    'unit.settlers':'Поселенцы', 'unit.worker':'Рабочий', 'unit.explorer':'Исследователь', 'unit.warrior':'Воин',
    'unit.slinger':'Пращник', 'unit.archer':'Лучник', 'unit.spearman':'Копейщик', 'unit.horseman':'Всадник',
    'unit.chariot':'Колесница', 'unit.elephant':'Боевой слон', 'unit.catapult':'Катапульта',
    'unit.trebuchet':'Требушет', 'unit.galley':'Галера', 'unit.galleon':'Галеон',
    'unit.workboat':'Рабочая лодка', 'unit.frigate':'Фрегат', 'unit.knight':'Рыцарь',
    'unit.pikeman':'Пикинёр', 'unit.longbow':'Длинный лук', 'unit.fencer':'Фехтовальщик',
    'unit.swordsman':'Мечник', 'unit.trireme':'Трирема', 'unit.city':'Город',
    'unit.destroyed_city':'Разрушенный город', 'unit.generic':'Отряд', 'unit.city_badge':'ГОРОД',
    'unit.units_count':'Отряды ({count})', 'unit.units_at':'Отряды: {i}, {j}',
    'unit.features':'{attack}/{defense}/{speed}', 'unit.selected_military':'Выбрано военных отрядов: {count}',
    'unit.id':'ID отряда: {id}', 'unit.pending':'ожидается',
    'terrain.water':'Вода', 'terrain.sand':'Песок', 'terrain.grass':'Равнина', 'terrain.snow':'Снег',
    'terrain.hills':'Холмы', 'terrain.mountains':'Горы', 'terrain.forest':'Лес',
    'terrain.grasswater':'Равнина с водой', 'terrain.unknown':'Неизвестно',
    'tile.defence':'Защита', 'tile.base':'Базовый доход', 'tile.resource':'Ресурс', 'tile.current':'Сейчас',
    'tile.suggested':'Рекомендуется', 'tile.after':'После',
    'tile.income':'Еда {food} / Щиты {production} / Золото {gold}',
    'cost.unit_upkeep':'Содержание отрядов', 'cost.city_balances':'Баланс городов за ход',
    'cost.city':'Город', 'cost.population':'Нас.', 'cost.producing':'Производство',
    'cost.balance_food_production_gold':'Баланс Е/П/З', 'cost.no_cities':'Нет городов',
    'cost.improvement_upkeep':'Содержание улучшений',
    'cost.each_food_gold':'На один Е/З', 'cost.total_food_gold':'Всего Е/З',
    'cost.each_food_production_gold':'На одно Е/П/З', 'cost.total_food_production_gold':'Всего Е/П/З',
    'cost.no_units':'Нет отрядов',
    'civilization.coat_title':'Герб {name}', 'civilization.own_suffix':' ({you})',
    'civilization.units_cities':'Отряды: {units} | Города: {cities}',
    'civilization.food_gold':'Еда: {food} | Золото: {gold}',
    'civilization.results':'Убито: {killed} | Захвачено: {occupied} | Разрушено: {destroyed}',
    'civilization.relation_to_you':'Отношение к вам: {relation}',
    'relation.friend':'Друг', 'relation.enemy':'Враг', 'relation.neutral':'Нейтрально', 'relation.self':'Своя',
    'technology.science_rate':'Наука: {rate}%', 'technology.research_unavailable':'Исследование недоступно',
    'technology.status':'Технология: {name} {progress}/{cost}', 'technology.all_discovered':'Все технологии открыты',
    'technology.Mining':'Горное дело', 'technology.Pottery':'Гончарное дело',
    'technology.Animal Husbandry':'Животноводство', 'technology.Sailing':'Мореплавание',
    'technology.Masonry':'Каменная кладка', 'technology.Bronze Working':'Обработка бронзы',
    'technology.Irrigation':'Орошение', 'technology.Writing':'Письменность', 'technology.Archery':'Стрельба из лука',
    'technology.Wheel':'Колесо', 'technology.Astronomy':'Астрономия', 'technology.Currency':'Деньги',
    'technology.Horseback Riding':'Верховая езда', 'technology.Iron Working':'Обработка железа',
    'technology.Shipbuilding':'Кораблестроение', 'technology.Mathematics':'Математика',
    'technology.Navigation':'Навигация', 'technology.Construction':'Строительство', 'technology.Engineering':'Инженерия',
    'resource.bananas':'Бананы', 'resource.cattle':'Скот', 'resource.copper':'Медь', 'resource.crabs':'Крабы',
    'resource.deer':'Олени', 'resource.fish':'Рыба', 'resource.rice':'Рис', 'resource.sheep':'Овцы',
    'resource.stone':'Камень', 'resource.wheat':'Пшеница', 'resource.amber':'Янтарь', 'resource.citrus':'Цитрусы',
    'resource.cotton':'Хлопок', 'resource.dyes':'Красители', 'resource.diamonds':'Алмазы', 'resource.furs':'Меха',
    'resource.gypsum':'Гипс', 'resource.honey':'Мёд', 'resource.incense':'Благовония', 'resource.ivory':'Слоновая кость',
    'resource.marble':'Мрамор', 'resource.olives':'Оливки', 'resource.pearls':'Жемчуг', 'resource.salt':'Соль',
    'resource.silk':'Шёлк', 'resource.silver':'Серебро', 'resource.spices':'Пряности', 'resource.sugar':'Сахар',
    'resource.tea':'Чай', 'resource.turtles':'Черепахи', 'resource.whales':'Киты', 'resource.wine':'Вино',
    'resource.horses':'Лошади', 'resource.iron':'Железо', 'resource.gold':'Золото', 'resource.gems':'Самоцветы',
    'turn.end_ai_user':'Завершить ход ИИ {id}', 'turn.end_user':'Завершить ход игрока {id}',
    'auth.login_or_email':'Логин или почта', 'auth.login':'Войти', 'auth.email_optional':'Почта (необязательно)',
    'auth.password':'Пароль', 'auth.remember_me':'Запомнить меня', 'auth.register':'Регистрация',
    'auth.register_heading':'Регистрация игрока', 'auth.register_new':'Зарегистрировать нового игрока',
    'auth.return_login':'Вернуться ко входу', 'auth.login_failed':'Не удалось войти.',
    'auth.registration_failed':'Не удалось зарегистрироваться.',
    'auth.cookie_rejected':'Браузер отклонил cookie игры. Разрешите cookie для этого сайта.',
    'auth.session_replaced':'В эту учётную запись вошли с другого устройства. Войдите снова.',
    'auth.session_expired':'Сеанс истёк. Войдите снова.', 'auth.invalid_session':'Сеанс недействителен. Войдите снова.',
    'auth.authentication_required':'Войдите, чтобы продолжить.', 'auth.account_unavailable':'Учётная запись недоступна.',
    'message.disband_pending':'Отряд #{id} будет распущен в конце хода.',
    'message.unit_destroyed_funds':'Отряд «{name}» уничтожен из-за нехватки средств.',
    'message.worker_command_unavailable':'{command} недоступно рабочему #{id} на этой клетке.',
    'message.preparing_ai':'Подготовка игрока ИИ {id}...', 'message.ai_not_ready':'Игрок ИИ {id} не готов'
});
